# Generated by Django 6.0.3 on 2026-03-15 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='seccion',
            field=models.CharField(default='General', max_length=40),
        ),
    ]
