# Generated by Django 6.0.3 on 2026-04-04 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='rol',
            field=models.CharField(choices=[('lector', 'Lector'), ('autor', 'Autor')], default='lector', max_length=10),
        ),
    ]
